### ISSUE TITLE
Cannot Convert -> Object Reference not set

### ISSUE THREAD

**Issue by Jijaxxx** [Fei-Sheng-Wu/XlsxToHtmlConverter#1]
Hi Team, 
Thanks for the job that you are doing, I am having a issue when I tried to convert mu Excel to Html
on line 488
if (config.IsConvertHiddenSheet == false && currentSheet.State.Value != SheetStateValues.Visible)
-> Throw an Object Reference not set. Indeed, the currentSheet.State is null. 

If I comment this instruction. Nothing is happening. Getting a timeout. 
Thanks for your help. 
JJ

**Comment by Fei-Sheng-Wu** [comment]
Sorry, I will try to look into the issue and resolve it soon. Can you please share your Excel file for testing purposes?

**Comment by Jijaxxx** [comment]
[rdoa.xlsx](https://github.com/Fei-Sheng-Wu/XlsxToHtmlConverter/files/5316454/rdoa.xlsx)
Hi @Fei-Sheng-Wu , Many thanks for you answer. 
please find attached the file that I tried to convert. 
Many thanks

**Comment by Fei-Sheng-Wu** [comment]
Hi, the Excel file you provided can now be converted successfully with the newest update (version 1.1.12). This is what the conversion result looked like upon testing:

![output-html.jpg](https://user-images.githubusercontent.com/36951947/95002138-102fe000-058e-11eb-8d98-494d6f2bee49.jpg)

**Comment by Fei-Sheng-Wu** [comment]
@Jijaxxx

Also, we noticed you are using some text box in your excel file: 

![screen-snip-excel-file-text-box](https://user-images.githubusercontent.com/36951947/95002306-ad3f4880-058f-11eb-9bf4-d00f7c933a7d.jpg)

**Currently, we are not support textbox.** These text box are not same as the datas in the cells, they are on top of cells and overlap them.

But it is also a task in our features list and has a higher priority, it may be support in next release.

For now, you can just put these text into cells but not create a text box. We can convert cells data into html correctly.

If you still have any questions about text box, please create a new issue. I will close this issue now.

**Comment by Jijaxxx** [comment]
Look Great man. Many thanks. 
It works now.
