### ISSUE TITLE
Can't convert simple table to html

### ISSUE THREAD

**Issue by taraskuzyna** [Fei-Sheng-Wu/XlsxToHtmlConverter#2]
Hi!
I have run a test project and received these two bugs.

 -  `worksheet.DrawingsPart` is null in my case.
 - when I fixed first bug I received GENERAL value instead of numbers.

Test file: [test.xlsx](https://github.com/Fei-Sheng-Wu/XlsxToHtmlConverter/files/5341097/test.xlsx)
Result file: [test3.html.txt](https://github.com/Fei-Sheng-Wu/XlsxToHtmlConverter/files/5341121/test3.html.txt)

**Comment by Fei-Sheng-Wu** [comment]
@taraskuzyna

Thanks for using,

We will add your issue into our BUG list, it will be resolved within 3-5 days. Please wait patiently.

**Comment by Fei-Sheng-Wu** [comment]
Hi, this issue should be resolved with the newest update (version 1.1.14). The files you provided should now be able to be converted successfully.
