### ISSUE TITLE
DocumentFormat.OpenXml.Spreadsheet.Stylesheet.NumberingFormats.get response null.

### ISSUE THREAD

**Issue by NikZhukov** [Fei-Sheng-Wu/XlsxToHtmlConverter#4]
Hi Team,
Thanks for the job that you are doing, I am having a issue when I tried to convert mu Excel to Html
on line 790
System.NullReferenceException: "Object reference not set to an instance of an object."
DocumentFormat.OpenXml.Spreadsheet.Stylesheet.NumberingFormats.get response null.
[2.xlsx](https://github.com/Fei-Sheng-Wu/XlsxToHtmlConverter/files/6911634/2.xlsx)

**Comment by Fei-Sheng-Wu** [comment]
@NikZhukov

Thanks for using,

We will add your issue into our BUG list, it will be resolved within 3-5 days. Please wait patiently.

**Comment by Fei-Sheng-Wu** [comment]
Hi, this issue should be resolved now in the updated code (version 1.1.15). The exception should no longer occur. Please check if your problem is fixed.

**Comment by NikZhukov** [comment]
Hi Team,
Thanks for the job that you are doing.
I propose to expand the functionality of ConverterConfig:

IsConvertSheetNameVisible = false;
IsConvertFirstSheetOnly = false;
isConvertOnlyBody = false;

This can be very handy for quick integration into a page, for organizing document previews.

**Comment by Fei-Sheng-Wu** [comment]
Thanks for your feedback. I opened a new issue (Issue #5) for your three suggestions. I will try to implement them soon when I get the time to do so.

I will close this issue for now. Thanks.
