### ISSUE TITLE
"This stream from ZipArchiveEntry does not support seeking" error 

### ISSUE THREAD

**Issue by wladiz2001** [Fei-Sheng-Wu/XlsxToHtmlConverter#6]
In ConvertDrawings method:

Stream imageStream = imagePart.GetStream();
imageStream.Seek(0, SeekOrigin.Begin); <--- this line
byte[] data = new byte[imageStream.Length];
imageStream.Read(data, 0, (int)imageStream.Length);
string base64 = Convert.ToBase64String(data, Base64FormattingOptions.None);

generate the error: "This stream from ZipArchiveEntry does not support seeking"

I resolve that problem with this change

Stream imageStream = imagePart.GetStream();
if (imageStream.CanSeek) <--- change
    imageStream.Seek(0, SeekOrigin.Begin);
byte[] data = new byte[imageStream.Length];
imageStream.Read(data, 0, (int)imageStream.Length);
string base64 = Convert.ToBase64String(data, Base64FormattingOptions.None);

**Comment by Fei-Sheng-Wu** [comment]
This issue should now be resolved with the newest commit. Thank you very much.
